/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq;


import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Link;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.User;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.UserLink;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.LinkRecord;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.UserLinkRecord;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records.UserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinkRecord> CONSTRAINT_32 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_32"), new TableField[] { Link.LINK.ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_32A = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_32A"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<UserRecord> CONSTRAINT_3 = Internal.createUniqueKey(User.USER, DSL.name("CONSTRAINT_3"), new TableField[] { User.USER.CHAT_ID }, true);
    public static final UniqueKey<UserRecord> CONSTRAINT_36 = Internal.createUniqueKey(User.USER, DSL.name("CONSTRAINT_36"), new TableField[] { User.USER.USERNAME }, true);
    public static final UniqueKey<UserLinkRecord> CONSTRAINT_143 = Internal.createUniqueKey(UserLink.USER_LINK, DSL.name("CONSTRAINT_143"), new TableField[] { UserLink.USER_LINK.LINK_ID, UserLink.USER_LINK.CHAT_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserLinkRecord, LinkRecord> CONSTRAINT_1 = Internal.createForeignKey(UserLink.USER_LINK, DSL.name("CONSTRAINT_1"), new TableField[] { UserLink.USER_LINK.LINK_ID }, Keys.CONSTRAINT_32, new TableField[] { Link.LINK.ID }, true);
    public static final ForeignKey<UserLinkRecord, UserRecord> CONSTRAINT_14 = Internal.createForeignKey(UserLink.USER_LINK, DSL.name("CONSTRAINT_14"), new TableField[] { UserLink.USER_LINK.CHAT_ID }, Keys.CONSTRAINT_3, new TableField[] { User.USER.CHAT_ID }, true);
}
