services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=lwbeamer
      - POSTGRES_PASSWORD=2281337
      - POSTGRES_DB=scrapper
    volumes:
      - link-service-data:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=lwbeamer
      - --password=2281337
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=lwbeamer
      - RABBITMQ_DEFAULT_PASS=2281337
    volumes:
      - rabbitmq-state:/var/lib/rabbitmq
    networks:
      - backend


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - metrics

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - metrics

volumes:
  link-service-data:
  rabbitmq-state:
  prometheus:
  grafana:

networks:
  backend:
    name: backend
  metrics:
    name: metrics
