scrape_configs:
  - job_name: 'bot_prometheus_monitoring'
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'bot'

  - job_name: 'scrapper_prometheus_monitoring'
    metrics_path: '/metrics'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8092']
        labels:
          application: 'scrapper'
